In [1]:
import pandas as pd
import numpy as np

In [2]:
# read in the dataset

df = pd.read_csv('/Users/juhee/Desktop/GA/Submissions/Projects/project_3-master/data/reddit.csv')

In [3]:
# check shape and the first 5 rows

print(df.shape)
df.head()

(6000, 78)

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,distinguished,steward_reports,removed_by,associated_award,body,is_submitter,link_id,parent_id,collapsed_because_crowd_control,top_awarded_type
0,[],True,1SissyMan-Ad3388,NaN,[],NaN,text,t2_7pxsctd6,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,jackaquack,NaN,[],NaN,text,t2_bkq1v,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Sudden_Judgment_9864,NaN,[],NaN,text,t2_7tg0h9i8,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,TitillatingTittyLady,NaN,[],NaN,text,t2_5kxbh25s,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,indranil98,NaN,[],NaN,text,t2_2mkj8e02,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# check the column names - we only would like to keep necessary columns

df.columns

Index(['all_awardings', 'allow_live_comments', 'author',
       'author_flair_css_class', 'author_flair_richtext', 'author_flair_text',
       'author_flair_type', 'author_fullname', 'author_patreon_flair',
       'author_premium', 'awarders', 'can_mod_post', 'contest_mode',
       'created_utc', 'domain', 'full_link', 'gildings', 'id',
       'is_crosspostable', 'is_meta', 'is_original_content',
       'is_reddit_media_domain', 'is_robot_indexable', 'is_self', 'is_video',
       'link_flair_background_color', 'link_flair_richtext',
       'link_flair_text_color', 'link_flair_type', 'locked', 'media_only',
       'no_follow', 'num_comments', 'num_crossposts', 'over_18',
       'parent_whitelist_status', 'permalink', 'pinned', 'pwls',
       'retrieved_on', 'score', 'selftext', 'send_replies', 'spoiler',
       'stickied', 'subreddit', 'subreddit_id', 'subreddit_subscribers',
       'subreddit_type', 'thumbnail', 'title', 'total_awards_received',
       'treatment_tags', 'upvote_ratio', 'url', 'whitelist_status', 'wls',
       'link_flair_template_id', 'link_flair_text', 'post_hint', 'preview',
       'removed_by_category', 'author_flair_template_id',
       'author_flair_text_color', 'author_flair_background_color', 'edited',
       'banned_by', 'author_cakeday', 'distinguished', 'steward_reports',
       'removed_by', 'associated_award', 'body', 'is_submitter', 'link_id',
       'parent_id', 'collapsed_because_crowd_control', 'top_awarded_type'],
      dtype='object')

In [5]:
# check the columns we might be interested in --> will keep subreddit, selftext, title, body, num_comments

df[['subreddit', 'selftext', 'title', 'body', 'domain', 'is_crosspostable', 'is_original_content', 'num_comments']]

,subreddit,selftext,title,body,domain,is_crosspostable,is_original_content,num_comments
0,relationship_advice,I'am a bi 58 year old male. I have not came ...,BI 58 Male Caught With Guy,NaN,self.relationship_advice,True,False,0.0
1,legaladvice,"Not looking for advice, just a question. If so...",When a dealer gets arrested do his roommates g...,NaN,self.legaladvice,True,False,0.0
2,relationship_advice,\nUsing a throwaway cause my friends know my r...,My(14M) friend (14F) that Iâ€™ve been talking to...,NaN,self.relationship_advice,True,False,0.0
3,relationship_advice,"On mobile, kinda long sorry on advance. \n\nAp...",Did my boyfriend and I make the right assumpti...,NaN,self.relationship_advice,True,False,0.0
4,relationship_advice,Me (22M) and my partner(21f) have been in rela...,Tough patch in our relationship of four years,NaN,self.relationship_advice,True,False,0.0
...,...,...,...,...,...,...,...,...
5995,relationship_advice,NaN,NaN,&gt; He can walk away and refuse to pay child ...,NaN,NaN,NaN,NaN
5996,relationship_advice,NaN,NaN,You're ready to divorce over a friend she's on...,NaN,NaN,NaN,NaN
5997,legaladvice,NaN,NaN,OP was not entitled to child support. His mom...,NaN,NaN,NaN,NaN
5998,relationship_advice,NaN,NaN,you being coerced into continuing a relationsh...,NaN,NaN,NaN,NaN
5999,relationship_advice,NaN,NaN,"Iâ€™m not sure if this helps, but she didnâ€™t mov...",NaN,NaN,NaN,NaN

In [6]:
df = df[['subreddit', 'selftext', 'title', 'body']]

In [8]:
df.head()

,subreddit,selftext,title,body
0,relationship_advice,I'am a bi 58 year old male. I have not came ...,BI 58 Male Caught With Guy,NaN
1,legaladvice,"Not looking for advice, just a question. If so...",When a dealer gets arrested do his roommates g...,NaN
2,relationship_advice,\nUsing a throwaway cause my friends know my r...,My(14M) friend (14F) that Iâ€™ve been talking to...,NaN
3,relationship_advice,"On mobile, kinda long sorry on advance. \n\nAp...",Did my boyfriend and I make the right assumpti...,NaN
4,relationship_advice,Me (22M) and my partner(21f) have been in rela...,Tough patch in our relationship of four years,NaN

In [9]:
# check how many 

df.groupby('subreddit').count()

                     selftext  title  body
subreddit
legaladvice              1008   1034   497
relationship_advice      1945   1966  2503

In [10]:
# check missing values

df.isnull().sum()

subreddit       0
selftext     3047
title        3000
body         3000
dtype: int64

In [11]:
# check unique value counts of each column

len(df.subreddit.unique())

2

In [12]:
len(df.selftext.unique())

2708

In [13]:
len(df.title.unique())

2981

In [14]:
len(df.body.unique())

2925

In [16]:
# we only care about the words used in posts, no matter title, selftext, or body

# fill null values as an empty string

df.fillna(' ', inplace = True)

# create a column that contains all three as text_all

df['text_all'] = df['title'] + ' ' + df['selftext'] + '  ' + df['body']

In [17]:
# create a y column as a target variable

df['y'] = np.where(df['subreddit'] == 'relationship_advice', 1, 0)

In [18]:
# check to see if y variable has been created

df.head()

,subreddit,selftext,title,body,text_all,y
0,relationship_advice,I'am a bi 58 year old male. I have not came ...,BI 58 Male Caught With Guy,,BI 58 Male Caught With Guy I'am a bi 58 year o...,1
1,legaladvice,"Not looking for advice, just a question. If so...",When a dealer gets arrested do his roommates g...,,When a dealer gets arrested do his roommates g...,0
2,relationship_advice,\nUsing a throwaway cause my friends know my r...,My(14M) friend (14F) that Iâ€™ve been talking to...,,My(14M) friend (14F) that Iâ€™ve been talking to...,1
3,relationship_advice,"On mobile, kinda long sorry on advance. \n\nAp...",Did my boyfriend and I make the right assumpti...,,Did my boyfriend and I make the right assumpti...,1
4,relationship_advice,Me (22M) and my partner(21f) have been in rela...,Tough patch in our relationship of four years,,Tough patch in our relationship of four years ...,1

In [19]:
# check null values again

df.isnull().sum()

subreddit    0
selftext     0
title        0
body         0
text_all     0
y            0
dtype: int64

In [20]:
# save this cleaned dataset to csv

df.to_csv('/Users/juhee/Desktop/GA/Submissions/Projects/project_3-master/data/reddit_clean.csv', index = False)